#sample configuration
env:
  name: frozenlake
  kwargs:
    map_name: "8x8"
    is_slippery: true
    #render_mode: "human"
    #render_mode: null

seed: 42

wrappers:
  sparse_reward:
    enabled: false
    kwargs: {}

  #exploration:
    #enabled: true
    #method: intrinsic_count
    #kwargs:
      #bonus_coef: 0.05
  #exploration:
    #enabled: false
    #method: null
    #kwargs: {}
  #exploration:
    #enabled: true
    #method: icm
    #kwargs:
      #reward_scale: 0.001
      #icm_lr: 0.001
      #beta: 0.2
      #update_freq: 1000
      #feature_dim: 64
      #hidden_dim: 128
      #device: "cpu"
      #clip_intrinsic: null
  #exploration:
    #enabled: true
    #method: rnd
    #kwargs:
      #reward_scale: 0.001
      #rnd_lr: 0.001
      #update_freq: 1000
      #feature_dim: 64
      #hidden_dim: 128
      #device: "cpu"
  exploration:
    enabled: true
    method: logging_only
    kwargs: {}

agent:
  name: ppo
  kwargs:
    policy: "MlpPolicy"
    learning_rate: 0.0003
    gamma: 0.99
    ent_coef: 0.0
    verbose: 1
    tensorboard_log: "./wandb/logs"

train:
  total_timesteps: 500000 #500000

output:
  save_path: "checkpoints/ppo_frozenlake_medium"
  #save_path: "checkpoints/ppo_frozenlake_medium_count_intrinsic"
  #save_path: "checkpoints/ppo_frozenlake_medium_icm"
  #save_path: "checkpoints/ppo_frozenlake_medium_rnd"
  #best_save_path: "checkpoints/ppo_frozenlake_medium_rnd_best"
  #best_save_path: "checkpoints/ppo_frozenlake_medium_icm_best"
  best_save_path: "checkpoints/ppo_frozenlake_medium_best"
eval:
eval:
  num_episodes: 1000
  max_steps: 500
  model_path: "checkpoints/ppo_frozenlake_medium_best.zip"
  #model_path: "checkpoints/ppo_frozenlake_medium_entcoef.zip"
  #model_path: "checkpoints/ppo_frozenlake_medium_count_intrinsic.zip"
  #model_path: "checkpoints/ppo_frozenlake_medium_icm.zip"
  #model_path: "checkpoints/ppo_frozenlake_medium_rnd_best.zip"
  #model_path: "checkpoints/ppo_frozenlake_medium_icm_best.zip"

wandb:
  enabled: true
  project: "rl-frozenlake-benchmark"
  name: "ppo-none-frozenlake-v3"
  tags: ["frozenlake", "none"]