#sample configuration
env:
  name: frozenlake
  kwargs:
    map_name: "4x4"
    is_slippery: false

train:
  total_timesteps: 50000
  learning_rate: 0.0003
  gamma: 0.99
  ent_coef: 0.01
  verbose: 1

output:
  save_path: "checkpoints/ppo_frozenlake_medium"
