env:
  name: gridworld
  kwargs:
    width: 20
    height: 20
    start_pos: [0,0]
    goal_pos: [19,19]
    num_obstacles: 25
    random_seed: 52
    max_steps: 100

seed: 42

wrappers:
  sparse_reward:
    enabled: false
    kwargs: {}

  # exploration:
  #     enabled: true
  #     method: intrinsic_count
  #     kwargs:
  #       bonus_coef: 0.001
  # exploration:
  #   enabled: true
  #   method: icm
  #   kwargs:
  #     reward_scale: 0.01
  #     icm_lr: 0.0005
  #     beta: 0.2
  #     update_freq: 1000
  #     feature_dim: 32
  #     hidden_dim: 64
  #     device: "cpu"
  #     clip_intrinsic: 0.1
  # exploration:
  #   enabled: true
  #   method: rnd
  #   kwargs:
  #     reward_scale: 0.01
  #     rnd_lr: 0.0005
  #     update_freq: 1000
  #     feature_dim: 32
  #     hidden_dim: 64
  #     device: "cpu"

agent:
  name: ppo
  kwargs:
    policy: "MlpPolicy"
    learning_rate: 0.0001
    gamma: 0.99
    ent_coef: 0.1
    verbose: 1

train:
  total_timesteps: 500000

output:
  # save_path: "checkpoints/ppo_gridworld_easy"
  save_path: "checkpoints/ppo_gridworld_easy_entcoef"
  # save_path: "checkpoints/ppo_gridworld_easy_count_intrinsic"
  # save_path: "checkpoints/ppo_gridworld_easy_icm"
  # save_path: "checkpoints/ppo_gridworld_easy_rnd"
  # save_path: "checkpoints/ppo_gridworld_easy_timelimit"
  # save_path: "checkpoints/ppo_gridworld_easy_entcoef_timelimit"
  # save_path: "checkpoints/ppo_gridworld_easy_count_intrinsic_timelimit"
  # save_path: "checkpoints/ppo_gridworld_easy_icm_timelimit"
  # save_path: "checkpoints/ppo_gridworld_easy_rnd_timelimit"


eval:
  num_episodes: 5
  max_steps: 50
  # model_path: "checkpoints/ppo_gridworld_easy.zip"
  model_path: "checkpoints/ppo_gridworld_easy_entcoef.zip"
  # model_path: "checkpoints/ppo_gridworld_easy_count_intrinsic.zip"
  # model_path: "checkpoints/ppo_gridworld_easy_icm.zip"
  # model_path: "checkpoints/ppo_gridworld_easy_rnd.zip"
  # model_path: "checkpoints/ppo_gridworld_easy_timelimit.zip"
  # model_path: "checkpoints/ppo_gridworld_easy_entcoef_timelimit.zip"
  # model_path: "checkpoints/ppo_gridworld_easy_count_intrinsic_timelimit.zip"
  # model_path: "checkpoints/ppo_gridworld_easy_icm_timelimit.zip"
  # model_path: "checkpoints/ppo_gridworld_easy_rnd_timelimit.zip"
