env:
  name: metaworld
  kwargs:
    task_name: "reach-v3"
    render_mode: null

wrappers:
  #sparse_reward:
    #enabled: false
    #kwargs: {}
  sparse_reward:
    enabled: true
    kwargs:
      success_reward: 10.0
      failure_reward: 0.0

  #exploration:
    #enabled: false
    #method: null
    #kwargs: {}
  #exploration:
    #enabled: true
    #method: intrinsic_count
    #kwargs:
      #bonus_coef: 0.05
  exploration:
    enabled: true
    method: icm
    kwargs:
      reward_scale: 0.0001
      icm_lr: 0.0003
      beta: 0.5
      update_freq: 1000
      feature_dim: 64
      hidden_dim: 128
      device: "cpu"
      clip_intrinsic: 5.0
  #exploration:
    #enabled: true
    #method: rnd
    #kwargs:
      #reward_scale: 0.0001
      #rnd_lr: 0.001
      #update_freq: 1000
      #feature_dim: 64
      #hidden_dim: 128
      #device: "cpu"

agent:
  name: ppo
  kwargs:
    policy: "MlpPolicy"
    learning_rate: 0.0001
    gamma: 0.99
    ent_coef: 0.1
    verbose: 1

train:
  total_timesteps: 500000

output:
  #save_path: "checkpoints/ppo_metaworld_reach_sparse"
  #save_path: "checkpoints/ppo_metaworld_reach_sparse_rnd"
  #save_path: "checkpoints/ppo_metaworld_reach_sparse_counted"
  save_path: "checkpoints/ppo_metaworld_reach_sparse_icm"

eval:
  num_episodes: 100
  max_steps: 500
  #model_path: "checkpoints/ppo_metaworld_reach_sparse.zip"
  #model_path: "checkpoints/ppo_metaworld_reach_sparse_rnd.zip"
  #model_path: "checkpoints/ppo_metaworld_reach_sparse_counted.zip"
  model_path: "checkpoints/ppo_metaworld_reach_sparse_icm.zip"