env:
  name: metaworld
  kwargs:
    task_name: "reach-v3"
    render_mode: null

#wrappers:
  #sparse_reward:
    #enabled: true
    #kwargs:
      #success_reward: 50.0
      #threshold_rewards:
        #- [0.12, 0.05]
        #- [0.07, 0.1]
        #- [0.03, 0.5]
      #failure_reward: 0.0
      #use_dense_fallback: true
      #dense_coef: 0.005 
wrappers:
  sparse_reward:
    enabled: true
    type: "goal_threshold"
    kwargs:
      success_reward: 50.0
      threshold_rewards:
        - [0.12, 0.05]
        - [0.07, 0.1]
        - [0.03, 0.5]
      failure_reward: 0.0
      use_dense_fallback: true
      dense_coef: 0.005 #0.005

  #exploration:
    #enabled: false
    #method: null
    #kwargs: {}
  exploration:
    enabled: true
    method: intrinsic_count
    kwargs:
      bonus_coef: 0.05
  #exploration:
    #enabled: true
    #method: icm
    #kwargs:
      #reward_scale: 0.00002
      #icm_lr: 0.0001
      #beta: 0.2
      #update_freq: 2000
      #feature_dim: 64
      #hidden_dim: 128
      #device: "cpu"
      #clip_intrinsic: 1.0
  #exploration:
    #enabled: true
    #method: rnd
    #kwargs:
      #reward_scale: 0.00005
      #rnd_lr: 0.0003
      #update_freq: 2000
      #feature_dim: 64
      #hidden_dim: 128
      #device: "cpu"

agent:
  name: ppo
  kwargs:
    policy: "MlpPolicy"
    learning_rate: 0.0002
    gamma: 0.99
    ent_coef: 0.005
    verbose: 1

train:
  total_timesteps: 600000

output:
  #save_path: "checkpoints/ppo_metaworld_reach_sparse_icm"
  #save_path: "checkpoints/ppo_metaworld_reach_sparse"
  #save_path: "checkpoints/ppo_metaworld_reach_sparse_rnd"
  save_path: "checkpoints/ppo_metaworld_reach_sparse_counted"
  #best_save_path: "checkpoints/ppo_metaworld_reach_sparse_icm_best"
  #best_save_path: "checkpoints/ppo_metaworld_reach_sparse_best"
  #best_save_path: "checkpoints/ppo_metaworld_reach_sparse_rnd_best"
  best_save_path: "checkpoints/ppo_metaworld_reach_sparse_counted_best"


eval:
  num_episodes: 100
  max_steps: 500
  #model_path: "checkpoints/ppo_metaworld_reach_sparse_icm_best.zip"
  #model_path: "checkpoints/ppo_metaworld_reach_sparse_best.zip"
  #model_path: "checkpoints/ppo_metaworld_reach_sparse_rnd_best.zip"
  model_path: "checkpoints/ppo_metaworld_reach_sparse_counted_best.zip"

wandb:
  enabled: true
  project: "rl-exploration-benchmark"
  name: "ppo-icm-reach-v3-counted"
  tags: ["metaworld_reach-v3", "sparse", "counted_based"]